/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountRow: typeof import('./src/components/AccountRow.vue')['default']
    AccountsPage: typeof import('./src/components/AccountsPage.vue')['default']
    AccountsTable: typeof import('./src/components/AccountsTable.vue')['default']
  }
}
